kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonarqube
        deploymentconfig: sonarqube
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: sonarqube-1
          emptyDir: {}
        - name: sonarqube-2
          emptyDir: {}
        - name: sonarqube-3
          emptyDir: {}
        - name: sonarqube-4
          emptyDir: {}
      containers:
	  - env:
        - name: SONAR_VERSION
          value: 7.9.1
        - name: SONARQUBE_JDBC_USERNAME
          value: sonar
        - name: SONARQUBE_JDBC_PASSWORD
          value: sonar
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://postgresql..svc.cluster.local/sonarqube
        - name: SONAR_LOG_LEVEL
          value: INFO
        - name: sonarqube
          image: quay.io/dferreira/sonarqube:7.9.1
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: sonarqube-1
              mountPath: /opt/sonarqube/data
            - name: sonarqube-2
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-3
              mountPath: /opt/sonarqube/logs
            - name: sonarqube-4
              mountPath: /opt/sonarqube/temp
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
