apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"sonarqube:7.9.1","namespace":"sonarqube-oraex"},"fieldPath":"spec.template.spec.containers[?(@.name==\"sonarqube\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: sonarqube
    name: sonarqube
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: sonarqube
        deployment: sonarqube
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: sonarqube
          deployment: sonarqube
      spec:
        containers:
        - image: ' '
          name: sonarqube
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 9000
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /opt/sonarqube/data
            name: sonarqube-volume-1
          - mountPath: /opt/sonarqube/extensions
            name: sonarqube-volume-2
          - mountPath: /opt/sonarqube/logs
            name: sonarqube-volume-3
          - mountPath: /opt/sonarqube/temp
            name: sonarqube-volume-4
        volumes:
        - emptyDir: {}
          name: sonarqube-volume-1
        - emptyDir: {}
          name: sonarqube-volume-2
        - emptyDir: {}
          name: sonarqube-volume-3
        - emptyDir: {}
          name: sonarqube-volume-4
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: sonarqube
    name: sonarqube
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: sonarqube
      deployment: sonarqube
  status:
    loadBalancer: {}
kind: List
metadata: {}
