- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: sonarqube
    name: sonarqube
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: sonarqube
        deployment: sonarqube
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: sonarqube
          deployment: sonarqube
      spec:
        containers:
        - env:
          - name: SONAR_VERSION
            value: 7.9.1
          - name: SONARQUBE_JDBC_USERNAME
            value: sonar
          - name: SONARQUBE_JDBC_PASSWORD
            value: sonar
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://postgresql..svc.cluster.local/sonarqube
          - name: SONAR_LOG_LEVEL
            value: INFO
          image: quay.io/dferreira/sonarqube
          imagePullPolicy: IfNotPresent
          name: sonarqube
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 9000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/sonarqube/data
            name: sonarqube-volume-1
          - mountPath: /opt/sonarqube/extensions
            name: sonarqube-volume-2
          - mountPath: /opt/sonarqube/logs
            name: sonarqube-volume-3
          - mountPath: /opt/sonarqube/temp
            name: sonarqube-volume-4
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: sonarqube-volume-1
        - emptyDir: {}
          name: sonarqube-volume-2
        - emptyDir: {}
          name: sonarqube-volume-3
        - emptyDir: {}
          name: sonarqube-volume-4
