apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: sonarqube
  name: sonarqube-is
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/dferreira/sonarqube:7.9.1
    name: 7.9.1
