apiVersion: v1
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_USER = gitea
    RUN_MODE = prod

    [security]
    INTERNAL_TOKEN = "BIHTXpWreGhJzPKRvaZWDEQjqLAKnRrbQuxSmzTaEyiAjwhBTgODzlkmvPiOBWpDbXRRWmOCqTcLiSCCldgmpXgnhMXIrbcmfglrzXKyRE"
    INSTALL_LOCK   = true
    SECRET_KEY     = "fIEYIFIk"
    PASSWORD_COMPLEXITY = off

    [oauth2]
    ENABLE = false

    [database]
    DB_TYPE  = postgres
    HOST     = gitea-db:5432
    NAME     = gitea-db
    USER     = gitea
    PASSWD   = S00perSekretP@ssw0rd
    SSL_MODE = disable

    [repository]
    ROOT = /gitea-repositories

    [server]
    ROOT_URL         = http://gitea-oqss-cicd.apps.middleware.rhbr-lab.com/
    SSH_DOMAIN       = gitea-oqss-cicd.apps.middleware.rhbr-lab.com
    DOMAIN           = gitea-oqss-cicd.apps.middleware.rhbr-lab.com
    HTTP_PORT        = 3000
    SSH_PORT         = 2022
    DISABLE_SSH      = true
    START_SSH_SERVER = false
    LFS_START_SERVER = false
    OFFLINE_MODE     = false

    [mailer]
    ENABLED = false

    [service]
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    DISABLE_REGISTRATION              = false
    ENABLE_CAPTCHA                    = false
    REQUIRE_SIGNIN_VIEW               = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.example.org

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = true

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

    [session]
    PROVIDER = file

    [log]
    MODE      = file
    LEVEL     = Info
    ROOT_PATH = /home/gitea/log

    [markup.asciidoc]
    ENABLED = true
    FILE_EXTENSIONS = .adoc,.asciidoc
    RENDER_COMMAND = "asciidoc --out-file=- -"
    IS_INPUT_FILE = false
kind: ConfigMap
metadata:
  name: gitea-config
  
  labels:
    app: gitea
    app.kubernetes.io/component: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
    generator: helm
