kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-sonarqube
  labels:
    app: sonarqube
    chart: "sonarqube-0.1.1"
    release: "sonarqube"
    heritage: "Helm"

spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
