apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-install-plugins
  labels:
    app: sonarqube
    chart: sonarqube-0.1.1
    release: sonarqube
    heritage: Helm
data:
  install_plugins.sh: |-
    cd /opt/sonarqube/extensions/plugins/tmp
