apiVersion: v1
kind: Secret
metadata:
  name: postgresql-sonarqube
  labels:
    app: sonarqube
    chart: sonarqube-0.1.1
    release: sonarqube
    heritage: Helm
type: Opaque
data:
  postgresqlUsername: "c29uYXJVc2Vy"
  postgresqlPassword: "c29uYXJQYXNz"
  postgresqlDatabase: "c29uYXJEQg=="
