apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube
  labels:
    app: sonarqube
    chart: sonarqube-0.1.1
    release: sonarqube
    heritage: Helm
type: Opaque
data:
  username: "YWRtaW4="
  password: "YWRtaW4xMjM="
  currentAdminPassword: "YWRtaW4="