apiVersion: v1
kind: ConfigMap
metadata:
  name: nexussetup
  labels:
    app: nexus-setup
data:
  config-nexus.sh: |-    
    #!/bin/bash
    
    NS=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)
    NEXUS_USER=admin:admin123
    NEXUS_SVC_NAME=$(oc  -n ${NS} get svc -l app=sonatype-nexus -o name)
    NEXUS_URL=http://$( oc -n ${NS} get ${NEXUS_SVC_NAME} -o jsonpath --template='{.metadata.name}:{.spec.ports[].port}')
