apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-sonatype-nexus
spec:
  template:
    spec:
      containers:
        - name: nexus
          image: registry.connect.redhat.com/sonatype/nexus-repository-manager:3.39.0-ubi-1
          env:
            - name: install4jAddVmParams
              value: -Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
                -XX:+UseCGroupMemoryLimitForHeap
          livenessProbe:
            httpGet:
              path: /service/rest/v1/status
          readinessProbe:
            httpGet:
              path: /service/rest/v1/status
